# SoccerNet Camera Calibration - SynLoc Domain Adaptation
# Pathing
path: ./data/processed/yolo-calibration
train: images
val: images

# Keypoint Configuration (14 points: x, y, visibility)
kpt_shape: [14, 3] 

# Class Configuration
names:
  0: Pitch
