# SpiideoSynLoc Player Detection Configuration

# 1. Paths (Relative to where you run the YOLO command)
path: ./data/processed/yolo-synloc 
train: images/train  
val: images/val    # Change to images/valid if that is what your folder is named

# 2. Classes
names:
  0: Player